-- Create BOQ activities table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.boq_activities (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id UUID REFERENCES public.projects(id) ON DELETE CASCADE,
  project_code TEXT NOT NULL,
  project_sub_code TEXT,
  project_full_code TEXT,
  activity TEXT NOT NULL,
  activity_division TEXT,
  unit TEXT,
  zone_ref TEXT,
  zone_number TEXT,
  activity_name TEXT NOT NULL,
  total_units DECIMAL(15,2) DEFAULT 0,
  planned_units DECIMAL(15,2) DEFAULT 0,
  actual_units DECIMAL(15,2) DEFAULT 0,
  difference DECIMAL(15,2) DEFAULT 0,
  variance_units DECIMAL(15,2) DEFAULT 0,
  rate DECIMAL(15,2) DEFAULT 0,
  total_value DECIMAL(15,2) DEFAULT 0,
  planned_activity_start_date DATE,
  deadline DATE,
  calendar_duration INTEGER DEFAULT 0,
  activity_progress_percentage DECIMAL(5,2) DEFAULT 0,
  productivity_daily_rate DECIMAL(15,2) DEFAULT 0,
  total_drilling_meters DECIMAL(15,2) DEFAULT 0,
  drilled_meters_planned_progress DECIMAL(15,2) DEFAULT 0,
  drilled_meters_actual_progress DECIMAL(15,2) DEFAULT 0,
  remaining_meters DECIMAL(15,2) DEFAULT 0,
  activity_planned_status TEXT,
  activity_actual_status TEXT,
  reported_on_data_date BOOLEAN DEFAULT FALSE,
  planned_value DECIMAL(15,2) DEFAULT 0,
  earned_value DECIMAL(15,2) DEFAULT 0,
  delay_percentage DECIMAL(5,2) DEFAULT 0,
  planned_progress_percentage DECIMAL(5,2) DEFAULT 0,
  activity_planned_start_date DATE,
  activity_planned_completion_date DATE,
  activity_delayed BOOLEAN DEFAULT FALSE,
  activity_on_track BOOLEAN DEFAULT TRUE,
  activity_completed BOOLEAN DEFAULT FALSE,
  project_full_name TEXT,
  project_status TEXT,
  remaining_work_value DECIMAL(15,2) DEFAULT 0,
  variance_works_value DECIMAL(15,2) DEFAULT 0,
  lookahead_start_date DATE,
  lookahead_activity_completion_date DATE,
  remaining_lookahead_duration_for_activity_completion INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add some sample data for testing
INSERT INTO public.boq_activities (
  project_code, 
  activity_name, 
  activity_division, 
  unit, 
  total_units, 
  planned_units, 
  rate, 
  total_value,
  project_full_name,
  project_status
) VALUES 
(
  'P5001', 
  'Excavation Work', 
  'Civil', 
  'm3', 
  100, 
  50, 
  25.5, 
  2550,
  'Test Project 1',
  'on-going'
),
(
  'P5002', 
  'Concrete Work', 
  'Civil', 
  'm3', 
  200, 
  100, 
  45.0, 
  9000,
  'Test Project 2',
  'completed'
)
ON CONFLICT DO NOTHING;
